ALTER TYPE "TenantStatus" ADD VALUE IF NOT EXISTS 'DEPOSITED';

ALTER TABLE "Tenant"
ADD COLUMN IF NOT EXISTS "roommateCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "roommatePhone" TEXT;
